#!/bin/bash
# adresse dans le reseau avec R1 et R2
ip addr add 42.4.252.65/26 dev eth1
ip link set dev eth1 up
# adresse dans le reseau avec le service a acceder
ip addr add 42.4.252.4/26 dev eth0
ip link set dev eth0 up
#activer le routage
echo 1 > /proc/sys/net/ipv4/ip_forward

#route vers les reseaux autres que DMZ
#ip route add 0.0.0.0/0 via 42.4.252.66
#ip route add 0.0.0.0/0 via 42.4.252.67

#routage dynamique
service quagga start

iptables -P FORWARD DROP

iptables -A FORWARD -p icmp -j ACCEPT

iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -p tcp --sport 80 -j ACCEPT

iptables -A FORWARD -p tcp --dport 53 -j ACCEPT
iptables -A FORWARD -p tcp --sport 53 -j ACCEPT
iptables -A FORWARD -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -p udp --sport 53 -j ACCEPT
