#!/bin/bash
#addresse dans le reseau domestique
ip addr add 192.168.141.129/25 dev eth1
ip link set dev eth1 up
#addresse dans le reseau du FAI
ip addr add 42.4.252.194/26 dev eth0
ip link set dev eth0 up
#activation du routage
echo 1 > /proc/sys/net/ipv4/ip_forward
#route vers les autres reseaux
ip route add 0.0.0.0/0 via 42.4.252.193
#statut de dhcp
service isc-dhcp-server start

iptables -t nat -A POSTROUTING -s 192.168.141.128/25 -o eth0 -j MASQUERADE

iptables -P FORWARD DROP

iptables -A FORWARD -p icmp -j ACCEPT

iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -p tcp --sport 80 -j ACCEPT

iptables -A FORWARD -p tcp --dport 53 -j ACCEPT
iptables -A FORWARD -p tcp --sport 53 -j ACCEPT
iptables -A FORWARD -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -p udp --sport 53 -j ACCEPT



