#!/bin/bash
# adresse dans le DMZ
ip addr add 42.4.252.1/26 dev eth0
ip link set dev eth0 up
#route vers tous les reseaux via le FAI_access
ip route add 0.0.0.0/0 via 42.4.252.4

service apache2 start

